### ISSUE TITLE
[BUG] Users stuck when restoring from Old Seed Phrase during Multi-Backup restore

### ISSUE THREAD

**Issue by JeffreyDoyle** [onflow/FRW#13]
### Current Behavior

When a user attempts to restore their account using their extension seed phrase, if they mistakenly select to restore from seed phrase within the multi-backup workflow, they will get stuck unable to select their account to restore from.

![image (9)](https://github.com/Outblock/FRW/assets/14852344/e00bc1f2-e883-4e6e-83e5-4b8f1398d5d9)

### Expected Behavior

If the user selects to restore their account from recovery phrase within the multi-backup workflow, and they input a 12-word seed phrase and no accounts are found, we should redirect them to the restore "Flow Recovery Phrase (Old)" workflow so they can correctly recover their account.

### Steps To Reproduce

1. Select to restore account
2. Choose From Multi-Backup
3. Select iCloud/GDrive and Recovery Phrase
4. Input a 12 word recovery phrase
5. Observe that no accounts are displayed

### Environment

```markdown
- iOS
- Extension
```

**Comment by lmcmz** [comment]
@KK-UIUX  Need empty wallet list for this

**Comment by lmcmz** [comment]
@Peppermint1020 Let's retest and get network log

**Comment by lmcmz** [comment]
- [x] iOS
- [x] Android

**Comment by Peppermint1020** [comment]
This issue has been solved in both ios and android app. 

Now we allowed following process:
1. use 12 word phrase in multi-backup restore, pass.
2. use 15 word phrase in legacy backup restore, fail.
3. use other accounts 12 or 15 word phrase(not match with google drive or iCloud) in multi-backup restore, fail.

This issue is not closed yet, we also need to add empty wallet list.
