### ISSUE TITLE
Certain FT balances not displaying

### ISSUE THREAD

**Issue by JeffreyDoyle** [onflow/FRW#37]
### Current Behavior

For certain FTs such as, but not limited to, USDC, Beaver, Juice, their balances are not displaying correctly in Flow Wallet Extension.

### Expected Behavior

- When viewing a FT balance, it appears as expected within the wallet.

## Steps to Reproduce

- Open Flow Wallet Extension
- Observe the USDC balance not displayed correctly
- Select USDC
- Observe the USDC balance not displaying correctly

## Expected Outcomes

- [x] Token balances are displayed as expected

## Platforms

- [x] Extension

## Details:
![image (15)](https://github.com/user-attachments/assets/2f49ce78-538a-4926-a89b-35f358efd145)
![image (14)](https://github.com/user-attachments/assets/ed22594c-3a19-4987-8539-7a67abd6652c)

**Comment by Peppermint1020** [comment]
The error in token list cause this bug. Cadence failed in vault checking cadence because there are multiple FixesFungibleToken . 
Cao already fixed the script.
Now when viewing a FT balance, it appears as expected within the wallet.
<img width="412" alt="Screen Shot 2024-07-17 at 2 58 04 pm" src="https://github.com/user-attachments/assets/29d69bfa-86e1-4aae-8fdb-fdce3321f779">
<img width="406" alt="Screen Shot 2024-07-17 at 2 58 44 pm" src="https://github.com/user-attachments/assets/e451c250-0a08-4961-a48d-4a0e54cd0f88">
